### ISSUE TITLE
Loading skins lasts forever

### ISSUE THREAD

**Issue by dpikka** [klyte45/VehicleSkins#3]
Hello,
I'm not able to load any skins (even the default ones) because when I selected a vehicle, the message "Vehicle Skins is loading skins" appears but then nothing happenes.
I noticed an error in the ModTool that seems to be related to the Vehicle Skin.
I attached the screenshot and the Vehicle Skin log.

Regards,
dpikka

[VS.log.txt](https://github.com/klyte45/VehicleSkins/files/10202924/VS.log.txt)
![20221211192052_1](https://user-images.githubusercontent.com/120333155/206922146-b40b3252-cbfc-4f94-94bc-6fa2fe51f2ac.jpg)

**Comment by klyte45** [comment]
Take a look at latest version. This should be solved, or at least the problem will be another.
Anyway, the loading shall not be forever anymore, even with errors

**Comment by dpikka** [comment]
Hello Klyte45,
Thanks for your attention.
I still have issue during the loading of the skins.
I attached the screenshot, the Vehicle Skin log and the output_log of the game.

If you need more information let me know.
I can also test beta version if you need.

Regards,
dpikka
[output_log.txt](https://github.com/klyte45/VehicleSkins/files/10669297/output_log.txt)
![1](https://user-images.githubusercontent.com/120333155/217091668-990a2912-3e5b-4c56-959b-a681b37cf1de.png)
[VS.log.txt](https://github.com/klyte45/VehicleSkins/files/10669303/VS.log.txt)

**Comment by klyte45** [comment]
Please check the version I just updated to WS. It was an issue with a folder with overwritten skins not being properly created.

Now this shall work well

**Comment by dpikka** [comment]
Hi,
Thanks for your support.

Now the mode works perfectly!

Regards,
Dp


Il mer 8 feb 2023, 00:03 Leandro Klyte ***@***.***> ha
scritto:
